---
openapi: 3.0.3
info:
  title: Secret Retriever
  description: Retrieves secrets
  version: 0.0.1
servers:
  - url: https://localhost:8443
paths:
  /v1/show:
    get:
      summary: Retrieve a secret
      operationId: service.secret.get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Secret'
        '4XX':
          description: Request error.
        '5XX':
          description: Unexpected error.
components:
  schemas:
    Secret:
      description: Retrieved secret.
      properties:
        secret:
          description: The secret.
          type: string
      required:
        - secret
